### ISSUE TITLE
Parse proc_macro tokens instead of strings

### ISSUE THREAD

**Issue by CAD97** [rust-lang/gll#110]
https://github.com/rust-lang/gll/blob/7c378f785d3886f95f5b4da040e137a018ebede4/macros/src/lib.rs#L10

https://github.com/rust-lang/gll/blob/7c378f785d3886f95f5b4da040e137a018ebede4/macros/src/lib.rs#L22

This string roundtripping causes `%%` to pass into the gll parser as `% %`, as with any other cluster of `Punct` which is `Joint` but not part of a Rust operator. As such, list syntax (#77) is currently defined with `"%" "%"` instead of the intended `"%%"`.

**Comment by eddyb** [comment]
I'm not sure it's the string round-tripping, though, I think `rustc`'s `proc_macro` server will not give you joint `%%`, only `proc-macro2` *might*.

**Comment by CAD97** [comment]
If all you do is parse the tokens and then look at the `TokenStream`, the joint-ness is respected. I'm actually using this in https://github.com/dtolnay/syn/pull/620 and https://github.com/cad97/pegcel

This did improve somewhat recently. Another fix would be in `proc_macro` itself to make the `Display` impl respect joint-ness properly (`proc_macro2`'s shim already does), but that's more involved.

**Comment by eddyb** [comment]
`%%` jointness doesn't seem to actually be respected yet, AFAICT, in my own testing.

**Comment by CAD97** [comment]
proc_macro2 runtime: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e66fe077c63f2d7e00f178fc5ec19b10 (Joint)

proc_macro compiletime: https://gist.github.com/CAD97/c4df7b1424a7f577bf8264a76bf2e1ab

Both respect Joint-ness, if you're losing it, it's somewhere else (likely `quote!`, as ``macro_rules!` _does_ always lose Joint-ness; `proc-quote` _may_ have fixed the issue but I haven't checked).
