### ISSUE TITLE
Enforce correctly-formatted code in CI.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/gll#79]
AFAIK this can be done with `cargo fmt --all` ~~and checking for dirty files under `src/` with `git`~~.

~~Is there a common setup for Rust projects that want to do this?
Or does everyone roll their own?~~

**EDIT**: @nrc provided a better solution in https://github.com/rust-lang/gll/issues/79#issuecomment-472574780

cc @centril

**Comment by eddyb** [comment]
Even worse, `cargo fmt --all` won't touch the template files, maybe we need to load them some other way so they show up as inputs?
Or move as much as possible into a support/runtime library instead of copying them.

**Comment by Centril** [comment]
cc @nrc

**Comment by nrc** [comment]
`cargo fmt --all --check` is the way to check formatting in CI. But yeah, it will only touch Rust files

**Comment by eddyb** [comment]
@nrc The "template" files are `.rs` and 100% Rust syntax (no parameters or anything).
I guess we can run `rustfmt --check src/generate/templates/*.rs`?

**Comment by nrc** [comment]
> @nrc The "template" files are .rs and 100% Rust syntax (no parameters or anything).

Sweet, should work fine. I'm not sure if rustfmt supports globs in arguments, it might, if not it would be a fairly simple PR.

**Comment by eddyb** [comment]
> I'm not sure if rustfmt supports globs in arguments, it might, if not it would be a fairly simple PR.

I'm hoping I can get Travis to pass it through a shell, nothing should have to support globs itself.
